######################################################################
# Automatically generated by qmake (2.01a) Fri Jun 14 15:04:13 2019
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . src ui headers
INCLUDEPATH += . headers headers_ui
UI_DIR = headers_ui

# Input
FORMS += ui/*.ui
SOURCES += src/*.cpp

